<?php

namespace App\Controllers;

use App\Models\Harga_bahanM;

class Harga_bahan extends BaseController
{
    protected $harga_bahanm, $data, $session;
    function __construct()
    {
        $this->harga_bahanm = new Harga_bahanM();
    }
    public function index()
    {
        $this->data = array('title' => 'Harga Bahan | Admin', 'breadcome' => 'Harga Bahan', 'url' => 'harga_bahan/', 'm_harga_bahan' => 'active bg-gradient-primary', 'session' => $this->session);

        echo view('App\Views\harga_bahan\harga_bahan_list', $this->data);
    }

    public function ajax_request()
    {
        $list = $this->harga_bahanm->get_datatables();
        $data = array();
        $no = isset($_GET['offset']) ? $_GET['offset'] + 1 : 1;
        foreach ($list as $rows) {
            $row = array();
            $row['id'] = $rows->id;
            $row['nomor'] = $no++;
            $row['bahan'] = $rows->bahan;
            $row['nama'] = $rows->nama;
            $row['nama_barang'] = $rows->nama_barang;
            $row['harga'] = rupiah($rows->harga);
            $row['satuan'] = $rows->satuan;
            $row['tanggal'] = $rows->tanggal;
            $data[] = $row;
        }
        $output = array(
            "total" => $this->harga_bahanm->total(),
            "totalNotFiltered" => $this->harga_bahanm->countAllResults(),
            "rows" => $data,
        );
        echo json_encode($output);
    }
    public function save()
    {
        switch ($this->request->getPost('action')) {
            case 'verifikasi':
                $id = $this->request->getPost('data');
                $data = array();
                foreach ($id as $key => $val) {
                    array_push($data, array(
                        'id' => $val,
                        'verified_at' => date('Y-m-d'),
                    ));
                }
                if ($this->harga_bahanm->updateBatch($data, 'id')) {
                    $status['type'] = 'success';
                    $status['text'] = 'Data Harga Bahan Telah Di Verfikasi';
                } else {
                    $status['type'] = 'error';
                    $status['text'] = $this->harga_bahanm->errors();
                }
                echo json_encode($status);
                break;
            case 'approve':
                $id = $this->request->getPost('data');
                $data = array();
                foreach ($id as $key => $val) {
                    array_push($data, array(
                        'id' => $val,
                        'approved_at' => date('Y-m-d'),
                    ));
                }
                if ($this->harga_bahanm->updateBatch($data, 'id')) {
                    $status['type'] = 'success';
                    $status['text'] = 'Data Harga Bahan Telah Di Setujui';
                } else {
                    $status['type'] = 'error';
                    $status['text'] = $this->harga_bahanm->errors();
                }
                echo json_encode($status);
                break;
            case 'unverifikasi':
                if ($this->harga_bahanm->unverifikasi($this->request->getPost('id'))) {
                    $status['type'] = 'success';
                    $status['text'] = '<strong>Di Kemablikan..!</strong>Berhasil';
                } else {
                    $status['type'] = 'error';
                    $status['text'] = '<strong>Oh snap!</strong> Proses kembalikan data gagal!';
                }
                echo json_encode($status);
                break;
            case 'delete':
                if ($this->harga_bahanm->delete($this->request->getPost('id'))) {
                    $status['type'] = 'success';
                    $status['text'] = '<strong>Deleted..!</strong>Berhasil dihapus';
                } else {
                    $status['type'] = 'error';
                    $status['text'] = '<strong>Oh snap!</strong> Proses hapus data gagal.';
                }
                echo json_encode($status);
                break;
        }
    }
}

/* End of file Harga_bahan.php */
/* Location: ./app/controllers/Harga_bahan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-07-07 09:31:01 */
/* http://harviacode.com */