<?php

namespace App\Controllers;

use App\Models\ApiModel;
use App\Models\Harga_bahanM;
use App\Models\HargaM;

class Harga extends BaseController
{
    protected $hargam, $harga_bahanm, $apimodel, $data, $session;
    function __construct()
    {
        $this->hargam = new HargaM();
        $this->harga_bahanm = new Harga_bahanM();
        $this->apimodel = new ApiModel();
    }
    public function index()
    {
        $this->data = array('title' => 'Daftar Harga | Admin', 'breadcome' => 'Daftar Harga', 'url' => 'harga/', 'm_harga' => 'active bg-gradient-primary', 'session' => $this->session);

        echo view('App\Views\harga\harga_list', $this->data);
    }

    public function ajax_request()
    {
        $list = $this->hargam->get_datatables();
        $data = array();
        $no = isset($_GET['offset']) ? $_GET['offset'] + 1 : 1;
        foreach ($list as $rows) {
            $row = array();
            $row['nomor'] = $no++;
            $row['id_bahan'] = $rows->id_bahan;
            $row['nama'] = $rows->nama_barang;
            $row['harga'] = rupiah($rows->harga_barang);
            $row['satuan'] = $rows->satuan;
            $row['ket'] = $rows->ket;
            $row['tanggal'] = $rows->tanggal;
            $data[] = $row;
        }
        $output = array(
            "total" => $this->hargam->total(),
            "totalNotFiltered" => $this->hargam->total(),
            "rows" => $data,
        );
        echo json_encode($output);
    }
    public function save()
    {
        switch ($this->request->getPost('action')) {
            case 'kirim':
                $nama = $this->request->getPost('data');
                $data = array();
                $bahan = $this->request->getPost('bahan');
                foreach ($nama as $key => $val) {
                    $id = $val['id_bahan'];
                    $api = $this->apimodel->getApi('https://sibakti.perdaginkop.bolmutkab.go.id/', "api-harga-barang/$bahan/$id")['text'];
                    foreach ($api as $item) {
                        $nama = explode(' ', strtolower($item['nama_barang']));
                        $tanggal = date('Y-m-d', strtotime($item['created_at']));
                        array_push($data, array(
                            'bahan' => $bahan,
                            'nama' => current($nama),
                            'nama_barang' => implode(' ', $nama),
                            'harga' => round($item['harga']),
                            'satuan' => strtolower($item['satuan']),
                            'tanggal' => $tanggal,
                        ));
                    }
                }
                if ($this->harga_bahanm->insertBatch($data)) {
                    $status['type'] = 'success';
                    $status['text'] = 'Data Harga Terkirim';
                } else {
                    $status['type'] = 'error';
                    $status['text'] = $this->harga_bahanm->errors();
                }
                echo json_encode($status);
                break;
        }
    }
}

/* End of file Pegawai.php */
/* Location: ./app/controllers/Pegawai.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-03-07 03:01:11 */
/* http://harviacode.com */