<?php

namespace App\Controllers;

use App\Models\KelasM;

class Kelas extends BaseController
{
    protected $kelasm, $data, $session;
    function __construct()
    {
        $this->kelasm = new KelasM();
    }
    public function index()
    {
        $this->data = array('title' => 'Kelas | Admin', 'breadcome' => 'Kelas', 'url' => 'kelas/', 'm_kelas' => 'active', 'session' => $this->session);

        echo view('App\Views\kelas\kelas_list', $this->data);
    }

    public function ajax_request()
    {
        $list = $this->kelasm->get_datatables();
        $data = array();
        $no = isset($_GET['offset']) ? $_GET['offset'] + 1 : 1;
        foreach ($list as $rows) {
            $row = array();
            $row['id'] = $rows->id;
            $row['nomor'] = $no++;
            $row['nama_kelas'] = $rows->nama_kelas;
            $data[] = $row;
        }
        $output = array(
            "total" => $this->kelasm->total(),
            "totalNotFiltered" => $this->kelasm->countAllResults(),
            "rows" => $data,
        );
        echo json_encode($output);
    }
    public function create()
    {
        $this->data = array('action' => 'insert', 'btn' => '<i class="fas fa-save"></i> Save');
        $num_of_row = $this->request->getPost('num_of_row');
        for ($x = 1; $x <= $num_of_row; $x++) {
            $data['nama'] = 'Data ' . $x;
            $this->data['form_input'][] = view('App\Views\kelas\form_input', $data);
        }
        $status['html']         = view('App\Views\kelas\form_modal', $this->data);
        $status['modal_title']  = 'Tambah Data Kelas';
        $status['modal_size']   = 'modal-lg';
        echo json_encode($status);
    }
    public function edit()
    {
        $id = $this->request->getPost('id');
        $this->data = array('action' => 'update', 'btn' => '<i class="fas fa-edit"></i> Edit');
        foreach ($id as $ids) {
            $get = $this->kelasm->find($ids);
            $data = array(
                'nama' => '<b>' . $get->nama . '</b>',
                'get' => $get,
            );
            $this->data['form_input'][] = view('App\Views\kelas\form_input', $data);
        }
        $status['html']         = view('App\Views\kelas\form_modal', $this->data);
        $status['modal_title']  = 'Update Data Kelas';
        $status['modal_size']   = 'modal-lg';
        echo json_encode($status);
    }
    public function save()
    {
        switch ($this->request->getPost('action')) {
            case 'insert':
                $nama = $this->request->getPost('nama');
                $data = array();
                foreach ($nama as $key => $val) {
                    array_push($data, array(
                        'nama_kelas' => $this->request->getPost('nama_kelas')[$key],
                    ));
                }
                if ($this->kelasm->insertBatch($data)) {
                    $status['type'] = 'success';
                    $status['text'] = 'Data Kelas Tersimpan';
                } else {
                    $status['type'] = 'error';
                    $status['text'] = $this->kelasm->errors();
                }
                echo json_encode($status);
                break;
            case 'update':
                $id = $this->request->getPost('id');
                $data = array();
                foreach ($id as $key => $val) {
                    array_push($data, array(
                        'id' => $val,
                        'nama_kelas' => $this->request->getPost('nama_kelas')[$key],
                    ));
                }
                if ($this->kelasm->updateBatch($data, 'id')) {
                    $status['type'] = 'success';
                    $status['text'] = 'Data Kelas Telah Di Ubah';
                } else {
                    $status['type'] = 'error';
                    $status['text'] = $this->kelasm->errors();
                }
                echo json_encode($status);
                break;
            case 'delete':
                if ($this->kelasm->delete($this->request->getPost('id'))) {
                    $status['type'] = 'success';
                    $status['text'] = '<strong>Deleted..!</strong>Berhasil dihapus';
                } else {
                    $status['type'] = 'error';
                    $status['text'] = '<strong>Oh snap!</strong> Proses hapus data gagal.';
                }
                echo json_encode($status);
                break;
        }
    }
}

/* End of file Kelas.php */
/* Location: ./app/controllers/Kelas.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-08-18 10:22:23 */
/* http://harviacode.com */