<?php

namespace App\Models;

use CodeIgniter\Model;

class FasilitasM extends Model
{
    protected $table = 'fasilitas';
    protected $allowedFields = array('lab', 'nama_fasilitas', 'jumlah', 'status', 'keterangan');
    protected $returnType     = 'object';
    protected $useSoftDeletes = false;

    protected $useTimestamps = true;
    protected $createdField  = 'created_at';
    protected $updatedField  = 'updated_at';
    protected $deletedField  = 'deleted_at';

    protected $validationRules = [
        'lab' => 'required|max_length[1]',
        'nama_fasilitas' => 'required|max_length[100]',
        'jumlah' => 'required|max_length[25]',
        'status' => 'required|max_length[11]',
        'keterangan' => 'max_length[255]',
    ];

    protected $validationMessages = [
        'lab' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal 1 Karakter'],
        'nama_fasilitas' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal 100 Karakter'],
        'jumlah' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal 25 Karakter'],
        'status' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal 11 Karakter'],
        'keterangan' => ['max_length' => 'Maximal 255 Karakter'],
    ];
    private function _get_datatables()
    {
        $column_search = array('lab', 'nama_fasilitas', 'jumlah', 'status', 'keterangan');
        $i = 0;
        foreach ($column_search as $item) { // loop column 
            if ($_GET['search']) {
                if ($i === 0) {
                    $this->groupStart();
                    $this->like($item, $_GET['search']);
                } else {
                    $this->orLike($item, $_GET['search']);
                }
                if (count($column_search) - 1 == $i)
                    $this->groupEnd();
            }
            $i++;
        }
        if (isset($_GET['order'])) {
            $this->orderBy($_GET['sort'], $_GET['order']);
        } else {
            $this->orderBy('id', 'asc');
        }
    }
    public function get_datatables()
    {
        $this->_get_datatables();
        $limit = isset($_GET['limit']) ? $_GET['limit'] : 0;
        $offset = isset($_GET['offset']) ? $_GET['offset'] : 0;
        return $this->findAll($limit, $offset);
    }
    public function total()
    {
        $this->_get_datatables();
        if ($this->tempUseSoftDeletes) {
            $this->where($this->table . '.' . $this->deletedField, null);
        }
        return $this->get()->getNumRows();
    }
}
/* End of file FasilitasM.php */
/* Location: ./app/models/FasilitasM.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-08-18 10:32:13 */