<?php

namespace App\Models;

use CodeIgniter\Model;

class GrafikM extends Model
{
    protected $table = 'harga_bahan';
    protected $allowedFields = array('bahan', 'nama', 'nama_barang', 'harga', 'satuan', 'tanggal', 'verified_at', 'approved_at');
    protected $returnType     = 'object';
    private function _get_datatables()
    {
        $column_search = array('bahan', 'nama', 'nama_barang', 'harga', 'satuan');
        $i = 0;
        foreach ($column_search as $item) { // loop column 
            if ($_GET['search']) {
                if ($i === 0) {
                    $this->groupStart();
                    $this->like($item, $_GET['search']);
                } else {
                    $this->orLike($item, $_GET['search']);
                }
                if (count($column_search) - 1 == $i)
                    $this->groupEnd();
            }
            $i++;
        }
        if (isset($_GET['order'])) {
            $this->orderBy($_GET['sort'], $_GET['order']);
        } else {
            $this->orderBy('id', 'asc');
        }
        $bahan = $_GET['bahan'];
        $this->where('bahan', $bahan);
        $this->where('approved_at !=', null);
    }
    public function get_datatables()
    {
        $this->_get_datatables();
        $limit = isset($_GET['limit']) ? $_GET['limit'] : 0;
        $offset = isset($_GET['offset']) ? $_GET['offset'] : 0;
        return $this->findAll($limit, $offset);
    }
    public function total()
    {
        $this->_get_datatables();
        if ($this->tempUseSoftDeletes) {
            $this->where($this->table . '.' . $this->deletedField, null);
        }
        return $this->get()->getNumRows();
    }
    public function unverifikasi($id)
    {
        $this->set('verified_at', null);
        $this->whereIn('id', $id);
        $this->update();
        return true;
    }

    public function verified()
    {
        return $this->where('verified_at !=', null);
    }
    public function approved()
    {
        $this->verified();
        return $this->where('approved_at !=', null);
    }
}
/* End of file Harga_bahanM.php */
/* Location: ./app/models/Harga_bahanM.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-07-07 09:31:01 */