<?php

namespace App\Models;

use CodeIgniter\Model;

class HargaM extends Model
{
    protected $table = 'unknown_database_lah';
    protected $apimodel, $harga_bahanm;
    function __construct()
    {
        $this->apimodel = new ApiModel();
        $this->harga_bahanm = new Harga_bahanM();
    }
    private function _get_datatables()
    {
        $bahan = $_GET['bahan'];
        $dataHarga = $this->harga_bahanm;
        // $data = $this->apimodel->getApi('http://localhost:8081/', "api-harga/$bahan/true")['text']; // local
        $data = $this->apimodel->getApi('https://sibakti.perdaginkop.bolmutkab.go.id/', "api-harga/$bahan/true")['text'];
        if (count($data) === 0) {
            return [];
        }
        foreach ($data as $row) {
            if ($dataHarga->where('nama_barang', strtolower($row['nama_barang']))->first()) continue;

            $newdata[] = $row;
        }
        return $newdata;
    }
    public function get_datatables()
    {
        $data = $this->_get_datatables();
        $limit = isset($_GET['limit']) ? $_GET['limit'] : 0;
        $offset = isset($_GET['offset']) ? $_GET['offset'] : 0;
        $search = $_GET['search'];
        $bahan = [];
        foreach ($data as $key => $row) {

            if ($offset > 0) {
                if ($key < $offset) continue;
            }

            if ($limit > 0) {
                if (($limit + $offset) == $key) break;
            }

            if ($search) {
                if (!str_contains(strtolower($row['nama_barang']), $search)) continue;
            }

            array_push($bahan, (object)[
                'id_bahan'      => $row['id_bahan_pokok'] ?? $row['id_bahan_penting'],
                'nama_barang'   => $row['nama_barang'],
                'harga_barang'  => $row['harga'],
                'satuan'        => $row['satuan'],
                'ket'           => $row['ket'],
                'tanggal'       => $row['created_at'],
            ]);
        }
        return $bahan;
    }
    public function total()
    {
        return count($this->_get_datatables());
    }
}
/* End of file PegawaiM.php */
/* Location: ./app/models/PegawaiM.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-03-07 03:01:11 */