<?php

namespace App\Models;

use CodeIgniter\Model;

class JadwalM extends Model
{
    protected $table = 'jadwal';
    protected $allowedFields = array('dosen_id', 'mk_id', 'kelas_id', 'lab_id', 'waktu_mulai', 'waktu_selesai', 'hari');
    protected $returnType     = 'object';
    protected $useSoftDeletes = false;

    protected $useTimestamps = true;
    protected $createdField  = 'created_at';
    protected $updatedField  = 'updated_at';
    protected $deletedField  = 'deleted_at';

    protected $validationRules = [
        'dosen_id' => 'required|max_length[]',
        'mk_id' => 'required|max_length[]',
        'kelas_id' => 'required|max_length[]',
        'lab_id' => 'required|max_length[]',
        'waktu_mulai' => 'required|max_length[]',
        'waktu_selesai' => 'required|max_length[]',
        'hari' => 'required|max_length[6]',
    ];

    protected $validationMessages = [
        'dosen_id' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal  Karakter'],
        'mk_id' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal  Karakter'],
        'kelas_id' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal  Karakter'],
        'lab_id' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal  Karakter'],
        'waktu_mulai' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal  Karakter'],
        'waktu_selesai' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal  Karakter'],
        'hari' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal 6 Karakter'],
    ];
    private function _get_datatables()
    {
        $column_search = array('dosen_id', 'mk_id', 'kelas_id', 'lab_id', 'waktu_mulai', 'waktu_selesai', 'hari');
        $i = 0;
        foreach ($column_search as $item) { // loop column 
            if ($_GET['search']) {
                if ($i === 0) {
                    $this->groupStart();
                    $this->like($item, $_GET['search']);
                } else {
                    $this->orLike($item, $_GET['search']);
                }
                if (count($column_search) - 1 == $i)
                    $this->groupEnd();
            }
            $i++;
        }
        if (isset($_GET['order'])) {
            $this->orderBy($_GET['sort'], $_GET['order']);
        } else {
            $this->orderBy('id', 'asc');
        }
    }
    public function get_datatables()
    {
        $this->_get_datatables();
        $limit = isset($_GET['limit']) ? $_GET['limit'] : 0;
        $offset = isset($_GET['offset']) ? $_GET['offset'] : 0;
        return $this->findAll($limit, $offset);
    }
    public function total()
    {
        $this->_get_datatables();
        if ($this->tempUseSoftDeletes) {
            $this->where($this->table . '.' . $this->deletedField, null);
        }
        return $this->get()->getNumRows();
    }
}
/* End of file JadwalM.php */
/* Location: ./app/models/JadwalM.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-08-19 11:40:00 */